const {
    attribute,
    autoGeneratedHashKey,
    table
  } = require('@aws/dynamodb-data-mapper-annotations');
  
@table(process.env.DYNAMODB_TABLE_NAME)
class Contact {
    @autoGeneratedHashKey()
    id;
  
    @attribute()
    name;
  
    @attribute()
    number;
}
  
module.exports = Contact;