GET http://localhost:3001/api/phonebook

###
GET http://localhost:3001/info

###
DELETE http://localhost:3001/api/phonebook/1

###
GET http://localhost:3001/api/phonebook/1

###
POST http://localhost:3001/api/phonebook/ HTTP/1.1
content-type: application/json

{
    "name": "Tester One",
    "number": "1236540978"
}