import config from './config';
import {
    attribute,
    autoGeneratedHashKey,
    table
  } from '@aws/dynamodb-data-mapper-annotations';

@table(config.dynamoDbTableName)
class Contact {
    @autoGeneratedHashKey()
    id!: string;
  
    @attribute()
    name!: string;
  
    @attribute()
    number!: string;
}
  
export { Contact };