name: Docker Build and Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          audience: sts.amazonaws.com
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::656805403368:role/PhonebookInfraStack-GitHubActionsRole4F1BBA26-noPenIsdZ4qG
          role-session-name: github-actions

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push Docker image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: phonebookinfrastack-phonebookrepositorye4baaf95-qganxdxt9ibk
        run: |
          docker buildx create --use
          docker buildx build --platform linux/amd64 -t $ECR_REGISTRY/$ECR_REPOSITORY:latest --push .

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          audience: sts.amazonaws.com
          aws-region: us-west-2
          role-to-assume: arn:aws:iam::656805403368:role/PhonebookInfraStack-GitHubActionsRole4F1BBA26-noPenIsdZ4qG
          role-session-name: github-actions

      - name: Update ECS Task Definition
        id: update-task-def
        run: |
          # Fetch the current task definition
          aws ecs describe-task-definition --task-definition PhonebookInfraStackPhonebookApplicationTaskDefA3A5156E > task-def.json
          
          # Update the container image with the latest tag
          NEW_TASK_DEF=$(jq --arg IMAGE "$ECR_REGISTRY/$ECR_REPOSITORY:latest" '.taskDefinition.containerDefinitions[0].image = $IMAGE' task-def.json | jq '.taskDefinition | del(.status, .taskDefinitionArn, .revision, .requiresAttributes, .compatibilities)')
          
          # Save the new task definition to a file
          echo $NEW_TASK_DEF > new-task-def.json
          
          # Register the new task definition
          aws ecs register-task-definition --cli-input-json file://new-task-def.json

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-service@v1
        with:
          service: PhonebookInfraStack-PhonebookApplicationService9EE5B926-Nz93NfvWh1vG
          cluster: PhonebookInfraStack-EcsDefaultClusterMnL3mNNYN926A5246-8SM6TbjyHvTk
          task-definition: PhonebookInfraStackPhonebookApplicationTaskDefA3A5156E
          wait-for-service-stability: true
          force-new-deployment: true
